// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSWrS4uGvjrM_F9FnRXbiPSj0av3DOYAg',
    appId: '1:465599434722:android:c12e68946aeb685b37f3bb',
    messagingSenderId: '465599434722',
    projectId: 'fluttercamp-67707',
    storageBucket: 'fluttercamp-67707.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKGhfJeqCgnV5fAw5HF9qzaKM5O5xVYCo',
    appId: '1:465599434722:ios:ad7377f25129dcb837f3bb',
    messagingSenderId: '465599434722',
    projectId: 'fluttercamp-67707',
    storageBucket: 'fluttercamp-67707.appspot.com',
    iosClientId: '465599434722-88ecirofjnvdgrn6u4vjc2ujqdmkgji1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCamp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKGhfJeqCgnV5fAw5HF9qzaKM5O5xVYCo',
    appId: '1:465599434722:ios:ad7377f25129dcb837f3bb',
    messagingSenderId: '465599434722',
    projectId: 'fluttercamp-67707',
    storageBucket: 'fluttercamp-67707.appspot.com',
    iosClientId: '465599434722-88ecirofjnvdgrn6u4vjc2ujqdmkgji1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCamp',
  );
}
